# Generated by Django 5.1.7 on 2025-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_category_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
